# Generated by Django 3.2.7 on 2021-09-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mymodel')),
            ],
        ),
    ]
